
package client1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BooksMagazineService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BooksMagazineService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OrderBooks")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "OrderBooks", targetNamespace = "http://services/", className = "client1.OrderBooks")
    @ResponseWrapper(localName = "OrderBooksResponse", targetNamespace = "http://services/", className = "client1.OrderBooksResponse")
    @Action(input = "http://services/BooksMagazineService/OrderBooksRequest", output = "http://services/BooksMagazineService/OrderBooksResponse")
    public String orderBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
